# Configuration for F1TENTH Gym simulation
particle_filter:
  ros__parameters:
    # Particle filter parameters (higher count for simulation accuracy)
    max_particles: 4000                # More particles for simulation precision
    max_viz_particles: 60              # Particles shown in RViz (performance optimization)
    max_range: 5.0                      # Maximum laser range in meters
    
    # Motion model noise parameters
    motion_dispersion_x: 0.05          # Noise in forward motion (m)
    motion_dispersion_y: 0.025         # Noise in lateral motion (m)
    motion_dispersion_theta: 0.25      # Noise in rotation (rad)
    
    # Robot geometry and sensor mounting
    lidar_offset_x: 0.288              # LiDAR forward offset from base_link (m)
    lidar_offset_y: 0.0                # LiDAR lateral offset from base_link (m)
    wheelbase: 0.324                   # Distance between front and rear axles (m)
    
    # Sensor model parameters (beam model)
    z_hit: 0.75      # Weight for correct measurements
    z_short: 0.01    # Weight for unexpected obstacles
    z_max: 0.07      # Weight for max range readings
    z_rand: 0.12     # Weight for random noise
    sigma_hit: 8.0   # Standard deviation for measurement noise
    
    # Ray-casting parameters
    range_method: "cddt"        # Distance transform method
    theta_discretization: 112   # Angular resolution for ray casting
    rangelib_variant: 2         # Ray casting library variant
    angle_step: 18              # Laser scan downsampling factor
    squash_factor: 2.2          # Weight normalization factor
    
    # Performance and debugging
    fine_timing: 0              # Enable detailed timing (0=off, 1=on)
    
    # ROS topic configuration (simulation specific)
    scan_topic: "/scan"                # LaserScan input topic
    # odom_topic: "/odom"                # Input odometry from real encoders/IMU
    odom_topic: "/ego_racecar/odom"    # Odometry from F1TENTH Gym simulation
    
    # Publishing options
    publish_odom: true                  # Publish pose as odometry message
    viz: true                           # Enable visualization markers
    timer_frequency: 100.0              # Timer update frequency (Hz) for motion interpolation
    
    # Update trigger thresholds
    update_min_distance: 0.0           # Min distance to trigger update (m)
    update_min_angle: 0.0              # Min rotation to trigger update (rad)
    
    # TF frame names
    map_frame: "map"                   # Global reference frame
    base_frame: "base_link"            # Robot base frame
    laser_frame: "laser"               # Laser scanner frame
    
map_server:
  ros__parameters:
    # Map selection for localization (SLAM-generated maps)
    # Available options:
    #   - levine: Multi-floor building map with complex geometry
    #   - Spielberg_map: Race track configuration 
    #   - map_1753950572: Custom SLAM-generated map from real data
    map: 'Spielberg_map'           # Selected map file (without .yaml extension)
