# Configuration for real F1TENTH car with SLAM generated maps
particle_filter:
  ros__parameters:
    # Particle filter parameters (optimized for real-time hardware performance)
    max_particles: 4000                # Total particles for localization (lower for real-time)
    max_viz_particles: 60              # Particles displayed in RViz (performance optimization)
    max_range: 5.0                     # Maximum laser range for processing (m)
    
    # Motion model noise parameters (tuned for real vehicle dynamics)
    motion_dispersion_x: 0.05          # Forward motion noise standard deviation (m)
    motion_dispersion_y: 0.025         # Lateral motion noise standard deviation (m)
    motion_dispersion_theta: 0.25      # Rotational motion noise standard deviation (rad)
    
    # Robot geometry and sensor mounting (F1TENTH physical dimensions)
    lidar_offset_x: 0.288              # LiDAR forward offset from base_link (m)
    lidar_offset_y: 0.0                # LiDAR lateral offset from base_link (m)
    wheelbase: 0.324                   # Distance between front and rear axles (m)
    
    # Sensor model parameters (beam model for real LiDAR)
    z_hit: 0.75      # Weight for correct measurements (primary component)
    z_short: 0.01    # Weight for unexpected obstacles/occlusion
    z_max: 0.07      # Weight for max range readings (open space)
    z_rand: 0.12     # Weight for random noise/spurious readings
    sigma_hit: 8.0   # Standard deviation for measurement noise (cm)
    
    # Ray-casting parameters (optimized for SLAM maps)
    range_method: "cddt"        # Compressed Distance Transform method
    theta_discretization: 112   # Angular resolution for ray casting lookup
    rangelib_variant: 2         # Ray casting library implementation variant
    angle_step: 18              # Laser scan downsampling factor (every 18th beam)
    squash_factor: 2.2          # Weight normalization/squashing factor
    
    # Performance and debugging options
    fine_timing: 0              # Detailed timing profiling (0=disabled, 1=enabled)
    
    # ROS topic configuration (real robot topics)
    scan_topic: "/scan"                # Input LaserScan topic from real LiDAR
    odom_topic: "/odom"                # Input odometry from real encoders/IMU
    
    # Publishing options
    publish_odom: true                  # Publish corrected pose as odometry
    viz: true                           # Enable RViz visualization markers
    timer_frequency: 100.0              # Timer update frequency (Hz) for motion interpolation
    
    # Update trigger thresholds (conservative for stability)
    update_min_distance: 0.0           # Minimum distance to trigger update (m)
    update_min_angle: 0.0              # Minimum rotation to trigger update (rad)
    
    # TF frame names (standard ROS conventions)
    map_frame: "map"                   # Global map coordinate frame
    base_frame: "base_link"            # Robot base coordinate frame
    laser_frame: "laser"               # Laser scanner coordinate frame
    
map_server:
  ros__parameters:
    # Map selection for localization (SLAM-generated maps)
    # Available options:
    #   - levine: Multi-floor building map with complex geometry
    #   - Spielberg_map: Race track configuration 
    #   - map_1753950572: Custom SLAM-generated map from real data
    map: 'map_1753950572'           # Selected map file (without .yaml extension)
